name: Updater

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 'litetex/xvm_default_config'
        token: ${{ secrets.PAT }}

    - name: Checkout code
      run: |
        curl -L https://gitlab.com/xvm/xvm/-/archive/master/xvm-master.zip?path=release/configs/default -o tmp.zip
        unzip tmp.zip
        rm tmp.zip
        mkdir -p config
        rm -r config/*
        mv -v xvm-master-release-configs-default/release/configs/default/* config/
        rm -r xvm-master-release-configs-default
        ls -lha
        ls -lha config

    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Add changes" -a
        git push origin
